version: "3.5"
volumes:
  node-ipc:
  node-db:
services:
  app:
    build: .
    environment:
      NETWORK: ${NETWORK:-preprod}
    volumes:
      - node-db:/data/db
      - node-ipc:/ipc
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"